parse_config:
  zmk_additional_includes:
    - "modules/zmk/helpers/include"
    - "config"

  zmk_preamble: |
    #include <zmk-helpers/key-labels/glove80.h>
    #define CONFIG_WIRELESS
    #include "misc/unicodes.dtsi"

  
  raw_binding_map:
    "&cancel_dot": "Cancel (Dot)"
    "&pulse_auto": "Pulse Auto"
    "&num_plus_nexus": "Num + Nexus"
    "&bnums_perma": "Num Perma"
    "&scr_slow": "Slow Scroll"
    "&scr_warp": "Warp Scroll"
    "&grave": "`"
    "&tilder": "~"
    "&senterer": "Shift Enterer"
    "&coolword": "Cool Caps Word"
    "&capvim": "2nd Vim Word"
    "&j_lock": "J Lock"
    "&f_lock": "F Lock"
    "&caret": "^"
    "&bpulse": "Base Pulse"
    "&sticky_w": "Sticky W"
    "&star": "*"
    "&att": "@"
    "&plus": "+"
    "&equal": "="
    "&percent": "%"
    "&bnums_plus": "Num Plus"
    "&quoter": '"'
    "&less": "<"
    "&greater": ">"
    "&qmark": "? (Enter)"
    "&exclaim": "! (Enter)"
    "&tabber": "‚≠æ"
    "&hash": "#"
    "&bslash": "\\"
    "&undctrl": "CTRL _"
    "&amp": "&"
    "&amp": "&"
    "&pipe": "|"
    "&deleter": Deleter
    "&cdeleter": Ctrl Deleter
    "&smart_q": Q
    "&oo_ak": √ñ (.)
    "&two_kps Q U": QU
    "&hold_navauto LEFT NAV_WORD": ‚Üê Auto
    "&hold_navauto RIGHT NAV_WORD": ‚Üí Auto
    "&hold_navauto DOWN NAV_WORD": ‚Üì Auto
    "&hold_navauto UP NAV_WORD": ‚Üë Auto
    "&nav_gui": Nav Gui
    "&kp C_PLAY_PAUSE": ‚èØ
    "&kp C_NEXT": ‚è≠
    "&kp C_PREV": ‚èÆ
    "&colon": ":"
    "&semi": ";"
    "&camps": "&"
    "&nav_guishift_macro": Nav Gui Shift
    "&nav_guictrl": Nav Gui Ctrl
    "&nav_alt": Nav Alt
    "&nav_ctrl": Nav Ctrl
    "&nav_ctrlshift_macro": Nav Ctrl Shift
    "&pag": Page Nav
    "&vim": Vim Nav
    "&enters": Enter
    "&escaper": Esc
    "&slash": /
    "&pcapsword": Dotted Caps Word
    "&ctrl_lock": Ctrl Lock
    "&aunav": Nav Word (au)
    "&lorshift": L (Shift)
    "&jl": J (L)
    "&eter": E LSHIFT (Enter)
    "&shift_repeat": Shift Repeat
    "&jl": J (L)
    "&eter": E LSHIFT (Enter)
    "&shift_repeat": Shift Repeat
    "&rshift_repeat": RShift Repeat
    "&to UNIC_LAYER": Unicode Layer
    "&thorn_eth": √û / √ê
    "&scrup_warp": Scroll ‚ñ≤ (Warp)
    "&scrdn_warp": Scroll ‚ñº (Warp)
    "&scrup_fast": Scroll ‚ñ≤ (Fast)
    "&scrdn_fast": Scroll ‚ñº (Fast)
    "&scrup_slow": Scroll ‚ñ≤ (Slow)
    "&scrdn_slow": Scroll ‚ñº (Slow)
    "&navigation": Nav Word
    "&nexus_auto": Nexus Auto
    "&tog UNDER_SPACE": _ space
    "&mpcaps": "Strong Caps Word"
    "&basecaps": "Caps Word"
    "&skalt": "Alt Sticky"
    "&skshift": "Shift Sticky"
    "&skgui": "Gui Sticky"
    "&skctrl": "Ctrl Sticky"
    "&cskalt": "Alt Sticky"
    "&cskshift": "Shift Sticky"
    "&cskgui": "Gui Sticky"
    "&cskctrl": "Ctrl Sticky"
    "&cs_pgup": "CtSh Page Up"
    "&cs_pgdn": "CtSh Page Down"
    "&ctrl_w": "Ctrl W"
    "&gui_tab": "Gui Tab"
    "&sgui_tab": "GuiSh Tab"
    "&ctrl_tab": "Ctrl Tab"
    "&sctrl_tab": "CtSh Tab"
    "&sqt_nex": "' Nexus"
    "&spacebase": Space Base
    "&tabbase": Tab Base
    "&enterbase": Enter Base
    "&leftbase": ‚Üê Base
    "&rightbase": ‚Üí Base
    "&downbase": ‚Üì Base
    "&upbase": ‚Üë Base
    "&sbase": S Base
    "&doller": "$"
    "&minusbase": "- Base"
    "&minusbase_eq": "- Base (=)"
    "&num_adaptive": Num Adapt
    "&bnav": Nav
    "&cnav": Nav
    "&bnexus": Base Nexus
    "&bsymbol": Base Symbol
    "&kp TAB": Tab
    "&tabs": Tab
    "&kp ENTER": Enter
    "&fnumwordp": Num Plus
    "&kp RA(Z)": √Ü
    "&kp RA(P)": √ñ
    "&kp RA(D)": √ê
    "&kp RA(T)": √û
    "&key_repeat": Repeat
    "&numword_autolayer NUM_WORD": Num Word
    "&adaptive": √Ü Adapt
    "&numsl": Num
    "&numsr": Num
    "&adaptive_up": ‚Üë (ak)
    "&ad_up": ‚Üë (ak)
    "&magic MAGIC BASE": Magic
    "&sl ICE": √çsl komma
    "&bspc_del": ‚å´ ‚å¶
    "&kp BACKSPACE": ‚å´
    "&kp DELETE": ‚å¶
    "&sl NUM_WORD": Sticky Num
    "&sl NEXUS": Nexus
    "&capsword": Caps Word
    "&mouse_hold_tap MOUSE MOUSE": Mouse
    "&scroll_speed_up": Scroll Speed ‚Üë
    "&scroll_speed_down": Scroll Speed ‚Üì
    "&mouse_slow": Slow
    "&mouse_fast": Fast
    "&mouse_warp": Warp
    "&page_up": PAGE ‚Üë
    "&page_down": PAGE ‚Üì
    "&kp CLEAR_AGAIN": Stay
    "&fnumword": Num Word
    "&fsl_num": Sticky Num
    "&fsl_num": Sticky Num
    "&kp C_MUTE": üîá
    "&volume_down": üîâ
    "&volume_up": üîä
    "&kp C_VOL_DN": "üîà‚¨á"
    "&kp C_VOL_UP": "üîä‚¨Ü"

    "&sys_reset": Reset
    "&bootloader": Boot
    "&caps_word": Caps Word

    "&bt BT_SEL 0": BT 1
    "&bt BT_SEL 1": BT 2
    "&bt BT_SEL 2": BT 3
    "&bt BT_SEL 3": BT 4

    "&kp LC(INS)": Copy
    "&kp LC(X)": Cut
    "&kp LS(INS)": Paste

    "&kp LG(LC(LEFT))": Prev Desk
    "&kp LG(LC(RIGHT))": Next Desk
    "&kp LG(LC(LS(A)))": Pin App
    "&kp LG(LC(LS(Q)))": Pin Win

    "&swapper": Next Win
    "&kp LS(TAB)": Prev Win
    "&dot_spc": Sentence
    "&num_dance": { "t": "Numword", "s": "Sticky Num" }
    "&magic_shift": { "t": Magic, "h": "Shift" }
    "&smart_mouse": Smart Mouse

    "&hml LS(LALT)TAB": Tab
    "&hm_combo_ldr": Leader
    "&hm_combo_ldrsh": Shift+Leader
    "&hm_combo_lpar": { "t": "(", "right": "<" }
    "&hm_combo_rpar": { "t": ")", "right": ">" }
    "&kp LBKT": "["
    "&kp RBKT": "]"

    "&mmv MOVE_UP": Mouse ‚Üë
    "&mmv MOVE_DOWN": Mouse ‚Üì
    "&mmv MOVE_LEFT": Mouse ‚Üê
    "&mmv MOVE_RIGHT": Mouse ‚Üí

    "&msc SCRL_UP": Scroll ‚Üë
    "&msc SCRL_DOWN": Scroll ‚Üì
    "&msc SCRL_LEFT": Scroll ‚Üê
    "&msc SCRL_RIGHT": Scroll ‚Üí

    "&mkp LCLK": Left Click
    "&mkp RCLK": Right Click
    "&mkp MCLK": Middle Click
    "&mkp MB4": Back Click
    "&mkp MB5": Forward Click

    # Unicode layer bindings ‚Üí rendered symbols
    "&uc alien_uc": "üëΩ"
    "&uc ufo_uc": "üõ∏"
    "&uc rocket_uc": "üöÄ"
    "&uc magic_wand_uc": "ü™Ñ"
    "&uc wizard_uc": "üßô"
    "&uc elf_uc": "üßù"
    "&uc vampire_uc": "üßõ"
    "&uc zombie_uc": "üßü"
    "&uc crystal_ball_uc": "üîÆ"
    "&uc sparkle_uc": "‚ú®"

    "&uc clown_uc": "ü§°"
    "&uc partying_face_uc": "ü•≥"
    "&uc joy_uc": "üòÇ"
    "&uc star_struck_uc": "ü§©"
    "&uc heart_eyes_uc": "üòç"
    "&uc exploding_head_uc": "ü§Ø"
    "&uc smirk_uc": "üòè"
    "&uc thinking_uc": "ü§î"
    "&uc scream_uc": "üò±"
    "&uc boom_uc": "üí•"
    "&uc skull_uc": "üíÄ"

    "&uc hear_no_evil_uc": "üôâ"
    "&uc ok_hand_uc": "üëå"
    "&uc brain_uc": "üß†"
    "&uc waving_hand_uc": "üëã"
    "&uc fire_combo_uc": "üî• üí•"
    "&uc dagger_uc": "‚Ä†"
    "&uc livelong_uc": "üññ"
    "&uc metal_uc": "ü§ò"
    "&uc turtle_uc": "üê¢"

    "&uc yinyang_uc": "‚òØ"
    "&uc pinched_fingers_uc": "ü§å"
    "&uc euro_uc": "‚Ç¨"
    "&uc palm_up_hand_uc": "ü´¥"
    "&uc less_combo_uc": "‚â§ ‚â™"
    "&uc saluting_face_uc": "ü´°"
    "&uc greater_combo_uc": "‚â• ‚â´"
    "&uc impliesiff_uc": "‚áí ‚áî"
    "&uc index_pointing_at_the_viewer_uc": "ü´µ"

    "&uc star_glow_uc": "üåü"
    "&uc 0x2764 0": "‚ù§"
    "&uc broken_heart_uc": "üíî"
    "&uc two_hearts_uc": "üíï"
    "&uc permille_uc": "‚Ä∞"
    "&uc sparkling_heart_uc": "üíñ"
    "&uc revolving_hearts_uc": "üíû"
    "&uc tada_uc": "üéâ"
    "&uc books_uc": "üìö"

    "&uc warning_uc": "‚ö†"
    "&uc exclamation_uc": "‚ùï ‚ùó"
    "&uc question_uc": "‚ùî ‚ùì"
    "&uc left_uc": "‚Üê"
    "&uc right_uc": "‚Üí"
    "&uc tradecopy_uc": "‚Ñ¢ ¬©"
    "&uc dice_uc": "üé≤"
    "&uc bullseye_uc": "üéØ"
    "&uc sob_skull_uc": "üò≠ üíÄ"
    "&uc down_uc": "‚Üì"
    "&uc up_uc": "‚Üë"
    "&uc underage_uc": "üîû"
    "&uc no_mobile_phones_uc": "üìµ"
    "&uc peace_uc": "‚òÆ"

    # Direct numeric example
    "&uc fire_combo_uc": "üî• üí•"

  trans_legend: { "t": "", "type": "trans" }

  zmk_combos:
    combo_cut: { align: bottom, o: 0.15 }
    combo_ldrsh: { align: top, o: 1.35 }

    combo_lt: { hidden: true }
    combo_gt: { hidden: true }
    combo_lbrc: { hidden: true }
    combo_rbrc: { hidden: true }

  zmk_keycode_map:
    # custom mappings
    LALT: Alt
    RALT: Alt
    LCTRL: Ctrl
    RCTRL: Ctrl
    LGUI: Gui
    RGUI: Gui
    LSHFT: Shift
    RSHFT: Shift

    BSPC: Bspc
    DEL: Del
    ESC: Esc
    RET: Enter
    SPACE: Spc
    TAB: Tab

    PG_UP: PgUp
    PG_DN: PgDn
    INS: Ins
    HOME: Home
    END: End

    UP: ‚Üë
    DOWN: ‚Üì
    LEFT: ‚Üê
    RIGHT: ‚Üí

    # C_MUTE: $$mdi:volume-off$$
    C_PP: $$mdi:play-pause$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-medium$$
    C_NEXT: $$mdi:skip-forward$$
    C_PREV: $$mdi:skip-backward$$

    # defaults
    AMPERSAND: "&"
    AMPS: "&"
    APOS: "'"
    APOSTROPHE: "'"
    ASTERISK: "*"
    ASTRK: "*"
    AT: "@"
    AT_SIGN: "@"
    BACKSLASH: \
    BSLH: \
    CARET: ^
    COLON: ":"
    COMMA: ","
    DLLR: $
    DOLLAR: $
    DOT: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    EQUAL: "="
    EXCL: "!"
    EXCLAMATION: "!"
    FSLH: /
    GRAVE: "`"
    GREATER_THAN: ">"
    GT: ">"
    HASH: "#"
    LBKT: "["
    LBRC: "{"
    LEFT_BRACE: "{"
    LEFT_BRACKET: "["
    LEFT_PARENTHESIS: (
    LESS_THAN: <
    LPAR: (
    LT: <
    MINUS: "-"
    NON_US_BACKSLASH: \
    NON_US_BSLH: "|"
    NON_US_HASH: "#"
    NUHS: "#"
    PERCENT: "%"
    PERIOD: .
    PIPE: "|"
    PIPE2: "|"
    PLUS: +
    POUND: "#"
    PRCNT: "%"
    QMARK: "?"
    QUESTION: "?"
    RBKT: "]"
    RBRC: "}"
    RIGHT_BRACE: "}"
    RIGHT_BRACKET: "]"
    RIGHT_PARENTHESIS: )
    RPAR: )
    SEMI: ;
    SEMICOLON: ;
    SINGLE_QUOTE: "'"
    SLASH: /
    SQT: "'"
    STAR: "*"
    TILDE: "~"
    TILDE2: "~"
    UNDER: _
    UNDERSCORE: _

draw_config:
  append_colon_to_layer_header: false
  dark_mode: true
  footer_text: "urob/zmk-config"
  physical_layout: glove80
